runner.dialect = scala213

maxColumn = 100

align.preset = more

continuationIndent.callSite = 2
continuationIndent.defnSite = 2

optIn.annotationNewlines = true
optIn.breakChainOnFirstMethodDot = true

verticalMultiline.atDefnSite = true
verticalMultiline.arityThreshold = 2

rewrite.rules = [
  PreferCurlyFors
  Imports,
  RedundantBraces
  RedundantParens
  SortModifiers
]
rewrite.imports.expand = true
rewrite.imports.sort = ascii
rewrite.imports.groups = [
  ["javax?..*", "scala..*"]
  [".*"]
  ["feed\\..*"]
]
rewrite.sortModifiers.order = [
  implicit
  final
  sealed
  abstract
  override
  private
  protected
  lazy
  open
  transparent
  inline
  infix
  opaque
]
runner.dialect = "scala213source3"
style = IntelliJ
trailingCommas = preserve
version=3.10.3