feed {
    postgres {
      url = "jdbc:postgresql://feed_service_postgres:5432/feed"
      user = "artrsyf"
      password = ${?POSTGRES_PASSWORD}
    }

    elastic {
      url = "http://feed_service_elastic:9200"
      listingIndexName = "listings"
    }

    minio {
      privateEndpoint = "http://feed-service-minio:9000"
      publicEndpoint = "http://localhost:9000"
      accessKey = ${?MINIO_ACCESS_KEY}
      secretKey = ${?MINIO_SECRET_KEY}
      bucket = "listings"
    }

    listing {
      limit = 50
      imagesLimit = 5
    }
}