feed {
    postgres {
      url = "jdbc:postgresql://feed_service_postgres:5432/feed"
      user = "artrsyf"
      password = ${?POSTGRES_PASSWORD}
    }

    elastic {
      url = "http://feed_service_elastic:9200"
      listingIndexName = "listing"
    }

    listing {
      limit = 50
    }
}