networks:
  feed_service_network:

services:
  feed_service:
    container_name: feed_service
    env_file:
      - ../secrets.env
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      feed_service_postgres:
        condition: service_started
      feed_service_elastic:
        condition: service_started
    networks:
      - feed_service_network

  feed_service_postgres:
    container_name: feed_service_postgres
    env_file:
      - ../postgres.env
    image: postgres:17-alpine
    volumes:
      - ../src/main/resources/db/migrations:/docker-entrypoint-initdb.d/
      - feed_service_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - feed_service_network

  feed_service_elastic:
    container_name: feed_service_elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    expose:
      - 9200
    networks:
      - feed_service_network

volumes:
  feed_service_postgres_data:
    driver: "local"
