networks:
  feed_service_network:

services:
  feed_service:
    container_name: feed_service
    env_file:
      - ../secrets.env
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      feed_service_postgres:
        condition: service_started
      feed_service_elastic:
        condition: service_started
      feed-service-minio:
        condition: service_started
    networks:
      - feed_service_network

  feed_service_postgres:
    container_name: feed_service_postgres
    env_file:
      - ../postgres.env
    image: postgres:17-alpine
    volumes:
      - ../src/main/resources/db/migrations:/docker-entrypoint-initdb.d/
      - feed_service_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - feed_service_network

  feed_service_elastic:
    container_name: feed_service_elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - feed_service_elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    expose:
      - 9200
    networks:
      - feed_service_network

  feed-service-minio:
    container_name: feed_service_minio
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    env_file:
      - ../minio.env
    ports:
      - "9001:9001"
    expose:
      - "9000"
    volumes:
      - feed_service_minio_data:/data
    networks:
      - feed_service_network

  feed_service_minio_proxy:
    image: nginx:alpine
    container_name: feed_service_minio_proxy
    ports:
      - "9000:9000"
    volumes:
      - ../nginx/minio.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - feed-service-minio
    networks:
      - feed_service_network

volumes:
  feed_service_postgres_data:
    driver: "local"
  feed_service_minio_data:
    driver: "local"
  feed_service_elastic_data:
    driver: "local"
